/**
 * @fileoverview gRPC-Web generated client stub for todoPackage
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: todo.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.todoPackage = require('./todo_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.todoPackage.TodoClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.todoPackage.TodoPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.todoPackage.TodoItem,
 *   !proto.todoPackage.TodoItem>}
 */
const methodDescriptor_Todo_createTodo = new grpc.web.MethodDescriptor(
  '/todoPackage.Todo/createTodo',
  grpc.web.MethodType.UNARY,
  proto.todoPackage.TodoItem,
  proto.todoPackage.TodoItem,
  /**
   * @param {!proto.todoPackage.TodoItem} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.todoPackage.TodoItem.deserializeBinary
);


/**
 * @param {!proto.todoPackage.TodoItem} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.todoPackage.TodoItem)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.todoPackage.TodoItem>|undefined}
 *     The XHR Node Readable Stream
 */
proto.todoPackage.TodoClient.prototype.createTodo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/todoPackage.Todo/createTodo',
      request,
      metadata || {},
      methodDescriptor_Todo_createTodo,
      callback);
};


/**
 * @param {!proto.todoPackage.TodoItem} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.todoPackage.TodoItem>}
 *     Promise that resolves to the response
 */
proto.todoPackage.TodoPromiseClient.prototype.createTodo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/todoPackage.Todo/createTodo',
      request,
      metadata || {},
      methodDescriptor_Todo_createTodo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.todoPackage.voidNoParams,
 *   !proto.todoPackage.TodoItems>}
 */
const methodDescriptor_Todo_readTodos = new grpc.web.MethodDescriptor(
  '/todoPackage.Todo/readTodos',
  grpc.web.MethodType.UNARY,
  proto.todoPackage.voidNoParams,
  proto.todoPackage.TodoItems,
  /**
   * @param {!proto.todoPackage.voidNoParams} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.todoPackage.TodoItems.deserializeBinary
);


/**
 * @param {!proto.todoPackage.voidNoParams} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.todoPackage.TodoItems)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.todoPackage.TodoItems>|undefined}
 *     The XHR Node Readable Stream
 */
proto.todoPackage.TodoClient.prototype.readTodos =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/todoPackage.Todo/readTodos',
      request,
      metadata || {},
      methodDescriptor_Todo_readTodos,
      callback);
};


/**
 * @param {!proto.todoPackage.voidNoParams} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.todoPackage.TodoItems>}
 *     Promise that resolves to the response
 */
proto.todoPackage.TodoPromiseClient.prototype.readTodos =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/todoPackage.Todo/readTodos',
      request,
      metadata || {},
      methodDescriptor_Todo_readTodos);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.todoPackage.voidNoParams,
 *   !proto.todoPackage.TodoItem>}
 */
const methodDescriptor_Todo_readTodosStream = new grpc.web.MethodDescriptor(
  '/todoPackage.Todo/readTodosStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.todoPackage.voidNoParams,
  proto.todoPackage.TodoItem,
  /**
   * @param {!proto.todoPackage.voidNoParams} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.todoPackage.TodoItem.deserializeBinary
);


/**
 * @param {!proto.todoPackage.voidNoParams} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.todoPackage.TodoItem>}
 *     The XHR Node Readable Stream
 */
proto.todoPackage.TodoClient.prototype.readTodosStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/todoPackage.Todo/readTodosStream',
      request,
      metadata || {},
      methodDescriptor_Todo_readTodosStream);
};


/**
 * @param {!proto.todoPackage.voidNoParams} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.todoPackage.TodoItem>}
 *     The XHR Node Readable Stream
 */
proto.todoPackage.TodoPromiseClient.prototype.readTodosStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/todoPackage.Todo/readTodosStream',
      request,
      metadata || {},
      methodDescriptor_Todo_readTodosStream);
};


module.exports = proto.todoPackage;

